In [1]:
import requests as rq
from time import sleep
import pandas as pd

In [2]:
cookies = {
    'frpo-cki': '"54bef4fd4bd87eeb"',
    '__cf_bm': 'gQ9Ukf2vKAD9uWWU1PJen_rE8jVGcquvRCZfv5evtUY-1781567074.5762923-1.0.1.1-t942NV.hpjIPFYjQul3S2Hpy8RgGCjBZA2ofK18XlyqLI3dAtcDrj0EOxLQHEpLxRqWmRxb55_GcqRZcPl2SE.TO1PS.gNKaAhTIdIcaW_XfnVxfFlekBaXDsfWvRwMm',
    '_gcl_au': '1.1.2093388990.1781567130',
    'client_id': 'undefined',
    '_ga': 'GA1.1.2119046841.1781567130',
    '_fbp': 'fb.2.1781567130028.51866585248795723',
    '_clck': '1wldp51%5E2%5Eg6x%5E0%5E2357',
    '_tt_enable_cookie': '1',
    '_ttp': '01KV6TT2THPRV01WK4RD8V9XJX_.tt.2',
    '_clsk': 'yx4crw%5E1781567148152%5E4%5E0%5Ee.clarity.ms%2Fcollect',
    'ttcsid_D7BUDTBC77U75VFHABP0': '1781567130452::4k-9HEa6wv9_knX_JsbX.1.1781567148290.1',
    'ttcsid': '1781567130452::DHjxsWmUDEBzekfKzfRW.1.1781567148290.0::1.17161.6063::29646.8.574.351::21085.25.0',
    '_ga_K7K8FVBZVB': 'GS2.1.s1781567129$o1$g1$t1781567169$j20$l0$h0',
    'g_state': '{"i_l":0,"i_ll":1781567169789,"i_b":"SInTCNbhBeDb85FKklFO/dxd5j91Mm6RT09OLkjNCQs","i_e":{"enable_itp_optimization":24},"i_et":1781567129329}',
}

headers = {
    'accept': 'application/json',
    'accept-language': 'es-ES,es;q=0.9',
    'content-type': 'application/json',
    'newrelic': 'eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjEyOTc1MjgiLCJhcCI6IjUwNDYzNDU5NSIsImlkIjoiZTY1MGQxMDNkMjliMTNkYiIsInRyIjoiNjkzZTlhNGYyNGEzNjU4MzNmMjcxNmE0ZTcwN2JjZDYiLCJ0aSI6MTc4MTU2NzE2OTg3NSwidGsiOiIzMTUxMjgifX0=',
    'origin': 'https://www.bumeran.com.pe',
    'priority': 'u=1, i',
    'referer': 'https://www.bumeran.com.pe/empleos-busqueda-sistemas.html',
    'sec-ch-ua': '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'traceparent': '00-693e9a4f24a365833f2716a4e707bcd6-e650d103d29b13db-01',
    'tracestate': '315128@nr=0-1-1297528-504634595-e650d103d29b13db----1781567169875',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36',
    'x-session-jwt': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI0YTRiNTc3MC02OTE0LTExZjEtODgwMS00ZDQ2ZTc5NWM3NzkiLCJpYXQiOjE3ODE1NjcxMjksImV4cCI6MTc4NDE1OTEyOX0.bUueNmhHWxOi_BVVDtsGukuzOVtjIQI6X-w_T6Wsjgk',
    'x-site-id': 'BMPE'}

params = {
    'pageSize': '20',
    'page': '0',
    'sort': 'RELEVANTES',
}

json_data = {
    'filtros': [],
    'query': '',
}
url = 'https://www.bumeran.com.pe/api/avisos/searchV2'

In [3]:

palabras_clave = [  "analista de datos",
    "data analyst",
    "cientifico de datos",
    "data scientist",
    "business intelligence",
    "bi",
    "data engineer",
    "ingeniero de datos",
    "programador",
    "desarrollador",
    "software engineer",
    "backend",
    "frontend",
    "full stack",
    "ingeniero de sistemas",
    "sistemas",
    "machine learning",
    "analytics"]
resultados_totales = []

for q in palabras_clave:
    print(f"\n--- Iniciando extracción para: {q} ---")
    
    # Reiniciar la página para cada nueva palabra clave
    page = 0
    json_data = {'filtros': [], 'query': q}
    
    while True:
        params['page'] = str(page)
        
        response = rq.post(url, json=json_data, headers=headers, params=params, cookies=cookies)
            
        data = response.json()
        empleos = data['content']
                
        #terminar el bucle si no existen más empleos
        if len(empleos) == 0:
            print(f"  Fin de resultados para '{q}'. Total páginas: {page}")
            break
                
        #agregar key con la palabra clave utilizada
        for empleo in empleos:
            empleo['palabra_clave'] = q
            resultados_totales.append(empleo)
                
        page += 1 #siguiente página
        sleep(1.5)


# 3. Conversión a DataFrame final
df_final = pd.DataFrame(resultados_totales)

--- Iniciando extracción para: analista de datos ---
  Fin de resultados para 'analista de datos'. Total páginas: 5

--- Iniciando extracción para: data analyst ---
  Fin de resultados para 'data analyst'. Total páginas: 1

--- Iniciando extracción para: cientifico de datos ---
  Fin de resultados para 'cientifico de datos'. Total páginas: 1

--- Iniciando extracción para: data scientist ---
  Fin de resultados para 'data scientist'. Total páginas: 2

--- Iniciando extracción para: business intelligence ---
  Fin de resultados para 'business intelligence'. Total páginas: 2

--- Iniciando extracción para: bi ---
  Fin de resultados para 'bi'. Total páginas: 3

--- Iniciando extracción para: data engineer ---
  Fin de resultados para 'data engineer'. Total páginas: 2

--- Iniciando extracción para: ingeniero de datos ---
  Fin de resultados para 'ingeniero de datos'. Total páginas: 1

--- Iniciando extracción para: programador ---
  Fin de resultados para 'programador'. Total páginas: 22

--- Iniciando extracción para: desarrollador ---
  Fin de resultados para 'desarrollador'. Total páginas: 22

--- Iniciando extracción para: software engineer ---
  Fin de resultados para 'software engineer'. Total páginas: 22

--- Iniciando extracción para: backend ---
  Fin de resultados para 'backend'. Total páginas: 3

--- Iniciando extracción para: frontend ---
  Fin de resultados para 'frontend'. Total páginas: 3

--- Iniciando extracción para: full stack ---
  Fin de resultados para 'full stack'. Total páginas: 3

--- Iniciando extracción para: ingeniero de sistemas ---
  Fin de resultados para 'ingeniero de sistemas'. Total páginas: 22

--- Iniciando extracción para: sistemas ---
  Fin de resultados para 'sistemas'. Total páginas: 12

--- Iniciando extracción para: machine learning ---
  Fin de resultados para 'machine learning'. Total páginas: 1

--- Iniciando extracción para: analytics ---
  Fin de resultados para 'analytics'. Total páginas: 3

In [4]:
df_final.columns

Index(['id', 'titulo', 'detalle', 'aptoDiscapacitado', 'idEmpresa', 'empresa',
       'confidencial', 'logoURL', 'validada', 'empresaPro',
       'fechaHoraPublicacion', 'fechaPublicacion', 'fechaModificado',
       'planPublicacion', 'portal', 'tipoTrabajo', 'idPais', 'idArea',
       'idSubarea', 'leido', 'visitadoPorPostulante', 'localizacion',
       'cantidadVacantes', 'guardado', 'gptwUrl', 'promedioEmpresa',
       'modalidadTrabajo', 'tienePreguntas', 'salarioObligatorio',
       'altaRevisionPerfiles', 'postulacionRapida', 'tipoAviso',
       'palabra_clave'],
      dtype='object')

In [5]:
df_final.shape

(2465, 33)

In [6]:
df_filtrado = df_final[['id','titulo', 'detalle','empresa',
       'fechaPublicacion', 'fechaModificado',
      'portal', 'tipoTrabajo','localizacion',
       'cantidadVacantes',
       'modalidadTrabajo', 
       'altaRevisionPerfiles',
       'palabra_clave']]
df_filtrado.head(3)

,id,titulo,detalle,empresa,fechaPublicacion,fechaModificado,portal,tipoTrabajo,localizacion,cantidadVacantes,modalidadTrabajo,altaRevisionPerfiles,palabra_clave
0,1118330494,Analista de Datos,¡Sé parte de Stefanini!​En Stefanini somos más...,STEFANINI PERU S.A,12-06-2026,19-06-2026 09:54:47,bumeran,Full-time,"San Borja, Lima",2,Presencial,False,analista de datos
1,1118337466,Analista de Datos (Educación),"Somos VISIVA (Certus,UCAL y Toulouse Lautrec) ...",VISIVA,18-06-2026,18-06-2026 15:24:42,bumeran,Full-time,"San Borja, Lima",1,Híbrido,False,analista de datos
2,1118337099,Analista de Datos e Integración,¡Únete a Qorikallpa!Somos el corporativo de AP...,APUCORP,18-06-2026,18-06-2026 16:20:42,bumeran,Full-time,"San Isidro, Lima",1,Presencial,False,analista de datos

In [7]:
duplicados = df_filtrado[df_filtrado.duplicated(subset=["id"])]
duplicados.head(3)

,id,titulo,detalle,empresa,fechaPublicacion,fechaModificado,portal,tipoTrabajo,localizacion,cantidadVacantes,modalidadTrabajo,altaRevisionPerfiles,palabra_clave
119,1118211146,Data Scientist/ Científico de Datos Retail y A...,&#x1f680; Data Scientist / Científico de Datos...,IBR PERU S.A.,27-03-2026,03-06-2026 08:32:52,bumeran,Full-time,"Lima, Lima",3,Presencial,False,data scientist
122,1118331827,Analista de Datos / Business Intelligence,¡Únete a una de las mejores empresas para trab...,Grupo Lucky,15-06-2026,19-06-2026 11:49:57,bumeran,Full-time,"Miraflores, Lima",2,Híbrido,False,business intelligence
127,1118307507,Analista de Datos / Business Intelligence,¡Únete a una de las mejores empresas para trab...,Grupo Lucky,26-05-2026,12-06-2026 10:17:46,bumeran,Full-time,"Miraflores, Lima",2,Híbrido,False,business intelligence

In [8]:
df_filtrado = df_filtrado.drop_duplicates(subset = ['id'], keep = "first")
df_filtrado.shape

(988, 13)

In [9]:
df_filtrado.to_csv("empleos_bumeran.csv", index = False)